### ISSUE TITLE
Calling SPARQLProcessor run throws a TypeError: get_all_item_data()

### ISSUE THREAD

**Issue by jermnelson** [KnowledgeLinks/rdfframework#21]
Attempted to test SPARQLProcessor from command-line Python:

<pre>
>>> from rdfframework.rml.processor import SPARQLProcessor`
>>> mapv4_processor = SPARQLProcessor(`
	    ["bf-to-map4.ttl",`
	    "D:/2018/dpla-service-hub/profiles/map4.ttl"],`
	    triplestore_url=TRIPLESTORE_URL)`
>>> mapv4_processor.run(item=rdflib.URIRef("https://digitalcc.coloradocollege.edu/islandora/object/coccc:8473"),
>>>     instance=rdlfib.URIRef("https://plains2peaks.org/0e9fa0e8-0ba2-11e8-8277-005056c00008"))
Traceback (most recent call last):`
  File "<pyshell#96>", line 2, in <module>`
    instance=instance)`
  File "d:\2018\rdfframework\rdfframework\rml\processor.py", line 935, in run
    debug=False)`
TypeError: get_all_item_data() missing 1 required positional argument: 'items'
</pre>

**Comment by mstabile75** [comment]
Fixed the call to get_all_item_data in the rml processor file. For a particular mapping the a paramaterization of the query may want to be cleaned depending on the data so that the results list doesn't balloon to large or data is missing.
kwargs 'filters' adds special filters and 'special_union' adds addtional method for adding more triples.
